### PR TITLE
S3Interviewquestions

### PR DESCRIPTION
**Pull request by Teja206**

### CODE REVIEW

**Review by Venky02189 — CHANGES_REQUESTED** [review]
add more interview questions

**Comment by HemanthKumarHK1806** [comment]
Add more questions related S3

**Review by HemanthKumarHK1806 — APPROVED** [review]
Add More questions for S3

**Review by HemanthKumarHK1806 — CHANGES_REQUESTED** [review]
Add More interview questions.

**Review by Venky02189 — COMMENTED** [review]
add answers

**Review by HemanthKumarHK1806 — APPROVED** [review]
Add More interview questions

**Review by HemanthKumarHK1806 — APPROVED** [review]
Approved

**Pull request closed without merging**
